name = "identidadartificial"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"

[vars]
GOOGLE_SEARCH_CONSOLE_SITE_URL = "sc-domain:identidadartificial.com"
