import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { basename, dirname, join } from 'node:path'
import { parse } from 'yaml'

export const BLOG_DIR = 'source/content/blog'
export const GENERATED_DIR = 'source/data/generated'

export async function readBlogPosts(blogDir = BLOG_DIR) {
  const files = (await readdir(blogDir)).filter(file => file.endsWith('.mdx')).sort()
  const posts = []

  for (const file of files) {
    const raw = await readFile(join(blogDir, file), 'utf8')
    const { data, body } = parseMdx(raw)
    posts.push({
      slug: basename(file, '.mdx'),
      title: data.title,
      description: data.description,
      category: data.category,
      tags: data.tags ?? [],
      body: cleanBody(body),
      generatedBy: data.generatedBy,
      generatedAt: data.generatedAt,
      promptBase: data.promptBase,
      humanReviewed: Boolean(data.humanReviewed),
      correctionNote: data.correctionNote,
      reviewNotes: data.reviewNotes,
      sourceQuality: data.sourceQuality,
      confidenceLevel: data.confidenceLevel,
      claimsReviewed: data.claimsReviewed,
    })
  }

  return posts
}

export function parseMdx(raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/)
  if (!match) {
    throw new Error('MDX file is missing YAML frontmatter')
  }

  return {
    data: parse(match[1]),
    body: match[2],
  }
}

export function cleanBody(body) {
  return body
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/\|.*\|/g, ' ')
    .replace(/[#>*_`[\]()]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

export async function writeGeneratedModule(path, exportName, value) {
  await mkdir(dirname(path), { recursive: true })
  const content = [
    '// Generated by build-time IA showcase scripts. Do not edit manually.',
    `export const ${exportName} = ${JSON.stringify(value, null, 2)} as const`,
    '',
  ].join('\n')
  await writeFile(path, content, 'utf8')
}

export function slugify(value) {
  return String(value)
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export function wordCount(text) {
  return text.trim().split(/\s+/).filter(Boolean).length
}
